version: '3'

services:
  db:
    image: postgres
    container_name: dbContainer
    environment:
      POSTGRES_PASSWORD: LoganTFE2023
      POSTGRES_USER: loganAdmin
      POSTGRES_DB: test
    ports:
     - "5433:5432"
    networks:
      - mynetwork
    volumes:
      - ./DB/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql

  backend:
    build:
      context: ./backend
    container_name: backendContainer
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - db
    command: sh -c "sleep 10 && node your-backend-entry-point.js"  # Ajout de la commande pour attendre 10 secondes avant de démarrer le backend

  frontend:
    build:
      context: ./frontend
    container_name: frontendContainer
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  mynetwork:
    driver: bridge
