version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: LoganTFE2023
      POSTGRES_USER: loganAdmin
      POSTGRES_DB: test
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    container_name: backendContainer
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontendContainer
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always