version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backendContainer
    networks:
      - reseau
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: frontendContainer
    networks:
      - reseau
    ports:
      - "3000:3000"

networks:
  reseau:
    driver: bridge
