version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backendContainer
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    container_name: frontendContainer
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
